### ISSUE TITLE
About train.txt and test.txt

### ISSUE THREAD

**Issue by liutumor** [syshin1014/VGN#3]
Hi Seung Yeon Shin, thank you for your source code!
I have get the STARE dataset according to your link.  Could you tell me how the train.txt or test.txt you construct? Because of my train.txt and test.txt is not reasonable, when I run the train_CNN.py, the variable  ' im_ext ' will referenced before assignment( util.py line 230).  I want to know the content of you STARE/train.txt and test.txt. 
Thank you very much!

**Comment by syshin1014** [comment]
Hi,
Those text files contain image file paths for training or test.
In the text file, each line has one file path.
For the STARE dataset, the file path should be like '/directory_you_use/im0001'.
This applies to all the other datasets.
Thanks.

**Comment by liutumor** [comment]
Thank you for your reply!
Another question, when I finished training CNN using STARE, the prob.png obtained by TEST_CNN was not ideal. There were two parallel lines above and below. 
My lables is vk.ppm supported by STARE,  the _mask.png generated by stare.exe->STARE->Mask->compute. Is it because of something wrong with my mask.png?

**Comment by syshin1014** [comment]
Do you mean lines in a result image?
I think those are not that important because the evaluation is usually conducted for pixels inside the FoV mask and easy to eliminate.
I used '.ah.ppm' images for training and test, and '.vk.ppm' images are used for human performance measurement.
Also, I used FoV masks generated by Oliveira et al. (2018) for STARE, which was mentioned in our MedIA paper.
